<a href="https://colab.research.google.com/github/officialkalpesh3170/PyTorch/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [8]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [10]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [12]:
scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)


In [13]:
X_train

array([[ 1.670359  ,  0.0703269 ,  1.67389666, ...,  1.52862767,
         0.16449149, -0.17661125],
       [ 0.26389026,  0.656419  ,  0.20680877, ...,  0.56413571,
        -0.40147282, -0.28887585],
       [ 0.0756228 , -0.63865548,  0.08194168, ...,  0.39013716,
         0.19778351,  0.2063111 ],
       ...,
       [-0.27599439, -0.92224844, -0.27298599, ..., -0.27255732,
         1.45970953,  0.13350584],
       [-0.73281987, -0.18727003, -0.75599276, ..., -0.74925335,
        -0.2984261 , -1.05916668],
       [ 1.23568264,  0.23811939,  1.20413945, ...,  0.50413621,
        -0.93097444, -0.54008181]])

Encoding Y as it has all categorical data
**bold text**



In [14]:
encoder = LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [86]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1])

**CONVERTING NUMPY ARRAY TO TENSORS**

In [16]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [87]:
X_train_tensor.shape

torch.Size([455, 30])

*Defining the model*

In [88]:
class MysimpleNN():
#initializing
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64, requires_grad=True)
    self.bias =torch.zeros(1,dtype=torch.float64,requires_grad=True)
#Forward pass


  def forward(self,X):
    X = X.to(torch.float64)
    z=torch.matmul(X,self.weights)+self.bias
    return torch.sigmoid(z)
# Loss

  def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    loss=-(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred))
    return loss.mean()

In [92]:
lr=0.1
epochs=300

In [90]:
model1 =MysimpleNN(X_train_tensor)

In [91]:
model1.weights

tensor([[0.7751],
        [0.2335],
        [0.9169],
        [0.1431],
        [0.1607],
        [0.1392],
        [0.5016],
        [0.1292],
        [0.1553],
        [0.8271],
        [0.4879],
        [0.0327],
        [0.4399],
        [0.1858],
        [0.4096],
        [0.4429],
        [0.6613],
        [0.6353],
        [0.6369],
        [0.7006],
        [0.9259],
        [0.3463],
        [0.9490],
        [0.9708],
        [0.2556],
        [0.3680],
        [0.6823],
        [0.8672],
        [0.8576],
        [0.5987]], dtype=torch.float64, requires_grad=True)

# Forward Pass

In [98]:

for epoch in range(epochs):

  # forward pass
  y_pred = model1.forward(X_train_tensor)

  # loss calculate
  loss = model1.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model1.weights -=lr * model1.weights.grad
    model1.bias -= lr * model1.bias.grad

  # zero gradients
  model1.weights.grad.zero_()
  model1.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')



Epoch: 1, Loss: 0.6691780997295431
Epoch: 2, Loss: 0.6691553818640656
Epoch: 3, Loss: 0.6691328697952944
Epoch: 4, Loss: 0.669110561204699
Epoch: 5, Loss: 0.6690884538035722
Epoch: 6, Loss: 0.6690665453325981
Epoch: 7, Loss: 0.6690448335614285
Epoch: 8, Loss: 0.6690233162882648
Epoch: 9, Loss: 0.6690019913394477
Epoch: 10, Loss: 0.6689808565690535
Epoch: 11, Loss: 0.6689599098584966
Epoch: 12, Loss: 0.6689391491161397
Epoch: 13, Loss: 0.6689185722769081
Epoch: 14, Loss: 0.6688981773019124
Epoch: 15, Loss: 0.6688779621780766
Epoch: 16, Loss: 0.6688579249177715
Epoch: 17, Loss: 0.6688380635584551
Epoch: 18, Loss: 0.668818376162318
Epoch: 19, Loss: 0.6687988608159348
Epoch: 20, Loss: 0.6687795156299207
Epoch: 21, Loss: 0.6687603387385943
Epoch: 22, Loss: 0.6687413282996447
Epoch: 23, Loss: 0.6687224824938055
Epoch: 24, Loss: 0.6687037995245311
Epoch: 25, Loss: 0.668685277617682
Epoch: 26, Loss: 0.6686669150212113
Epoch: 27, Loss: 0.6686487100048587
Epoch: 28, Loss: 0.6686306608598476
Epoc

In [94]:
model1.weights

tensor([[ 0.1715],
        [-0.0220],
        [ 0.3279],
        [-0.4490],
        [ 0.0718],
        [-0.2518],
        [-0.0155],
        [-0.3386],
        [-0.0384],
        [ 0.3667],
        [ 0.0086],
        [ 0.0135],
        [ 0.0350],
        [-0.1498],
        [ 0.0809],
        [-0.0245],
        [ 0.0162],
        [ 0.0166],
        [ 0.0299],
        [-0.0552],
        [ 0.1200],
        [ 0.0132],
        [ 0.1811],
        [ 0.1699],
        [-0.1195],
        [-0.0747],
        [ 0.0676],
        [ 0.1773],
        [ 0.0349],
        [-0.0473]], dtype=torch.float64, requires_grad=True)

# Y_prediction


In [107]:
# model evaluation
with torch.no_grad():
  y_pred = model1.forward(X_test_tensor)
  y_pred = (y_pred > 0.47).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6666666865348816
