<a href="https://colab.research.google.com/github/officialkalpesh3170/PyTorch/blob/main/Basics/dataLoadeers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing function

from sklearn.datasets import make_classification
import torch

In [3]:
X,y=make_classification(n_samples=10,n_features=2,n_informative=2,n_redundant=0,n_classes=2,random_state=42)

In [5]:
X.shape

(10, 2)

In [6]:
#converting the DataFramee to tensors

X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [7]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [8]:
from torch.utils.data import Dataset,DataLoader

In [9]:
#create class
class CustomDataset(Dataset):
   def __init__(self,x,y):
    self.features=X
    self.lables=y

   def __len__(self):

    return self.features.shape[0]

   def __getitem__(self,index):

    return self.features[index],self.lables[index]




In [10]:
dataset =CustomDataset(X,y)

In [11]:
len(dataset)

10

In [15]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True,num_workers=10)

/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


In [16]:
for i ,y in dataloader:
  print(i)
  print(y)

/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


tensor([[ 1.7774,  1.5116],
        [-0.7206, -0.9606]])
tensor([1, 0])
tensor([[-1.1402, -0.8388],
        [-1.9629, -0.9923]])
tensor([0, 0])
tensor([[ 1.0683, -0.9701],
        [ 1.8997,  0.8344]])
tensor([1, 1])
tensor([[ 1.7273, -1.1858],
        [-0.5872, -1.9717]])
tensor([1, 0])
tensor([[-2.8954,  1.9769],
        [-0.9382, -0.5430]])
tensor([0, 1])
