<a href="https://colab.research.google.com/github/officialkalpesh3170/PyTorch/blob/main/Basics/Pytorch_Autograde.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [ ]:
f=torch.randint(size=(3,2),low=0,high=10)
g=torch.randint(size=(2,3),low=0,high=10)

print(f)
print(g)

tensor([[5, 2],
        [8, 6],
        [4, 1]])
tensor([[4, 2, 7],
        [2, 5, 4]])


In [ ]:
torch.matmul(f,g)

tensor([[24, 20, 43],
        [44, 46, 80],
        [18, 13, 32]])

In [ ]:
torch.transpose(f,0,1)

tensor([[5, 8, 4],
        [2, 6, 1]])

In [ ]:
torch.sigmoid(f)

tensor([[0.9933, 0.8808],
        [0.9997, 0.9975],
        [0.9820, 0.7311]])

In [ ]:
torch.relu(f)

tensor([[5, 2],
        [8, 6],
        [4, 1]])

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.7456, 0.9254, 0.7946],
        [0.7255, 0.4930, 0.4259]])
tensor([[0.8791, 0.6359, 0.9313],
        [0.5896, 0.5253, 0.2809]])


In [ ]:
m+n

tensor([[1.6247, 1.5613, 1.7259],
        [1.3151, 1.0183, 0.7067]])

In [ ]:
torch.cuda.is_available()

True

**Reasoning**:
Load the necessary libraries for image processing and data manipulation.



In [ ]:
device=torch.device('cuda')

In [ ]:
torch.rand((2,3),device=device)

tensor([[0.3428, 0.7822, 0.2563],
        [0.0571, 0.8826, 0.1836]], device='cuda:0')

In [ ]:
x= torch.tensor(3.0,requires_grad=True)

In [ ]:
y=x**2

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
import math

def dz_dy(x):
  return 2*x*math.cos(x**2)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

In [2]:
# Inputs
x = torch.tensor(6.7)  # Input feature
y = torch.tensor(0.0)  # True label (binary)

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias

In [3]:
#Binary Cross Entropy Loss Scaler


def binary_cross_entropy_loss(prediction,target):
  epsilon=1e-8
  prediction=torch.clamp(prediction,epsilon,1-epsilon)
  return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))

In [4]:
#forward pass
z=w*x+b

y_pred=torch.sigmoid(z)


loss=binary_cross_entropy_loss(y_pred,y)

In [5]:
loss

tensor(6.7012)

In [8]:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)

dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

#2. d(y_pred)/dz
dy_pred_dz = y_pred * (1 - y_pred)

#3. d(z)/dw
dz_dw=x
dz_db=1

dl_dw=dloss_dy_pred*dy_pred_dz*dz_dw
dl_db=dloss_dy_pred*dy_pred_dz*dz_db

In [9]:
dl_dw

tensor(6.6918)

In [10]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

In [11]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [12]:
z=x*w+b

In [13]:
y_pred=torch.sigmoid(z)

In [14]:
loss = binary_cross_entropy_loss(y_pred,y)

In [15]:
loss.backward()

In [16]:
w.grad

tensor(6.6918)